name: CI - Pipeline Informatif

on: push

jobs:
  demo:
    name: Démonstration CI
    runs-on: Ndioba-runner
    env:
      STEP1: "Workflow-Initialisation"
    steps:
      - name: Étape 1 - Initialisation
        run: echo "Initialisation de ${STEP1}"

      - name: Étape 2 - Récupération du code
        run: echo "STEP2= ${{vars.VAR}}"

      - name: Étape 3 - Variables Secret
        run: echo "STEP3= ${{ Secret.STEP3 }}"

      - name: Étape 4 - Tests
        run: echo "Exécution des tests"

      - name: Étape 5 - Packaging
        run: echo "Packaging de l'application"

      - name: Étape 6 - Fin du pipeline
        run: echo "Pipeline terminé avec succès !"

      - name: Complete job
        run: echo "Le job est terminé."