name: CI -Pipeline Informatif

on: push:

    jobs:
      demo:
        name: Demonstration CI
        runs-on: Ndioba-runner
        steps:
          - name: Etape 1 - Initialisation
            run: echo "Initialisation du pipeline CI"

          - name: Etape 2 - Recuperation du code 
            run: echo "Recuperation du code "

          - name: Etape 3 - Build 
            run: echo "Build de l'application"

          - name: Etape 4 - Test
            run: echo "Execution des tests"

          - name: Etape 5 - Packaging
            run: echo "Packaging de l'application"

          - name: Etape 6 - Fin du pipeline
            run: echo "Pipeline CI termine avec succes !" 
